/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/post_by_query": {
    /** Returns the created post. */
    get: operations["api_v1_create_post_by_query"];
  };
  "/user": {
    /** Returns all users in the system. */
    get: operations["api_v1_get_all_users"];
    post: operations["api_v1_create_user"];
  };
  "/user/{id}": {
    /** Returns a single user by ID. */
    get: operations["api_v1_get_user"];
  };
  "/user_example": {
    /** Returns a single user by username. */
    get: operations["api_v1_get_user_by_name"];
  };
}

export interface components {
  schemas: {
    Post: {
      /** The unique identifier for the post. */
      post_id: number;
      /** A short summary of the post. */
      summary?: string | null;
      /** The title of the post. */
      title: string;
    };
    User: {
      email?: string | null;
      userId: number;
      username: string;
    };
  };
}

export interface operations {
  /** Returns the created post. */
  api_v1_create_post_by_query: {
    parameters: {
      form: {
        /** The unique identifier for the post. */
        post_id: number;
        /** A short summary of the post. */
        summary?: string | null;
        /** The title of the post. */
        title: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Post"];
        };
      };
      404: unknown;
    };
  };
  /** Returns all users in the system. */
  api_v1_get_all_users: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  api_v1_create_user: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
  };
  /** Returns a single user by ID. */
  api_v1_get_user: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      404: unknown;
    };
  };
  /** Returns a single user by username. */
  api_v1_get_user_by_name: {
    parameters: {
      query: {
        user_id: number;
        name: string;
        email?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      404: unknown;
    };
  };
}

export interface external {}
